// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	shop "biz/platform/api/internal/handler/shop"
	"biz/platform/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPut,
				Path:    "/",
				Handler: shop.CreateShopHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/shop"),
	)
}
