// Code generated by goctl. DO NOT EDIT.
// Source: main.proto

package server

import (
	"context"

	"core/authc/rpc/internal/logic"
	"core/authc/rpc/internal/svc"
	"core/authc/rpc/pb"
)

type ServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedServiceServer
}

func NewServiceServer(svcCtx *svc.ServiceContext) *ServiceServer {
	return &ServiceServer{
		svcCtx: svcCtx,
	}
}

// Login 用户登录
func (s *ServiceServer) Login(ctx context.Context, in *pb.LoginInput) (*pb.LoginOutput, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
