// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	auth "core/authz/api/internal/handler/auth"
	"core/authz/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/menus",
				Handler: auth.ListMenusHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/user/menu",
				Handler: auth.AddMenuHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/user/menu/:menuId",
				Handler: auth.RemoveMenuHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/roles",
				Handler: auth.ListRolesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/resources",
				Handler: auth.ListResourcesHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/authz"),
	)
}
