// Code generated by goctl. DO NOT EDIT.
// Source: main.proto

package server

import (
	"context"

	"unit/product/rpc/internal/logic"
	"unit/product/rpc/internal/svc"
	"unit/product/rpc/pb"
)

type ServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedServiceServer
}

func NewServiceServer(svcCtx *svc.ServiceContext) *ServiceServer {
	return &ServiceServer{
		svcCtx: svcCtx,
	}
}

// ListCategories 查询所有分类
func (s *ServiceServer) ListCategories(ctx context.Context, in *pb.ListCategoriesInput) (*pb.ListCategoriesOutput, error) {
	l := logic.NewListCategoriesLogic(ctx, s.svcCtx)
	return l.ListCategories(in)
}
