// Code generated by goctl. DO NOT EDIT.
// Source: main.proto

package server

import (
	"context"

	"core/member/rpc/internal/logic"
	"core/member/rpc/internal/svc"
	"core/member/rpc/pb"
)

type ServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedServiceServer
}

func NewServiceServer(svcCtx *svc.ServiceContext) *ServiceServer {
	return &ServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ServiceServer) Hello(ctx context.Context, in *pb.Empty) (*pb.Empty, error) {
	l := logic.NewHelloLogic(ctx, s.svcCtx)
	return l.Hello(in)
}
