// Code generated by goctl. DO NOT EDIT.
// Source: main.proto

package service

import (
	"context"

	"core/member/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty = pb.Empty

	Service interface {
		Hello(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultService struct {
		cli zrpc.Client
	}
)

func NewService(cli zrpc.Client) Service {
	return &defaultService{
		cli: cli,
	}
}

func (m *defaultService) Hello(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewServiceClient(m.cli.Conn())
	return client.Hello(ctx, in, opts...)
}
