// Code generated by goctl. DO NOT EDIT.
package types

type Role struct {
	RoleId     int64  `json:"roleId"`     // 角色ID
	Name       string `json:"name"`       // 角色名称
	Remark     string `json:"remark"`     // 备注
	CreatorId  int64  `json:"creatorId"`  // 创建者ID
	ShopId     int64  `json:"shopId"`     // 所属店铺ID
	SysType    int64  `json:"sysType"`    // 系统类型: 1-平台端,2-商家端,3-普通用户
	CreateTime int64  `json:"createTime"` // 创建时间
	UpdateTime int64  `json:"updateTime"` // 更新时间
}

type Resource struct {
	ResourceId int64  `json:"resourceId"` // 资源ID
	Name       string `json:"name"`       // 资源名称
	Method     string `json:"method"`     // 请求方法
	Pattern    string `json:"pattern"`    // 资源路径（ant style）
	SysType    int64  `json:"sysType"`    // 系统类型: 1-平台端,2-商家端,3-普通用户
	CreateTime int64  `json:"createTime"` // 创建时间
	UpdateTime int64  `json:"updateTime"` // 更新时间
}

type ListRolesReq struct {
}

type ListRolesResp struct {
	Roles []Role `json:"roles"`
}

type ListResourcesReq struct {
}

type ListResourcesResp struct {
	Resources []Resource `json:"resources"`
}
