// Code generated by goctl. DO NOT EDIT.
// Source: main.proto

package service

import (
	"context"

	"unit/shop/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddShopInput  = pb.AddShopInput
	AddShopOutput = pb.AddShopOutput
	Shop          = pb.Shop

	Service interface {
		// AddShop 创建店铺
		AddShop(ctx context.Context, in *AddShopInput, opts ...grpc.CallOption) (*AddShopOutput, error)
		// AddShopConfirm 创建店铺确认
		AddShopConfirm(ctx context.Context, in *AddShopInput, opts ...grpc.CallOption) (*AddShopOutput, error)
		// AddShopCancel 创建店铺回滚
		AddShopCancel(ctx context.Context, in *AddShopInput, opts ...grpc.CallOption) (*AddShopOutput, error)
	}

	defaultService struct {
		cli zrpc.Client
	}
)

func NewService(cli zrpc.Client) Service {
	return &defaultService{
		cli: cli,
	}
}

// AddShop 创建店铺
func (m *defaultService) AddShop(ctx context.Context, in *AddShopInput, opts ...grpc.CallOption) (*AddShopOutput, error) {
	client := pb.NewServiceClient(m.cli.Conn())
	return client.AddShop(ctx, in, opts...)
}

// AddShopConfirm 创建店铺确认
func (m *defaultService) AddShopConfirm(ctx context.Context, in *AddShopInput, opts ...grpc.CallOption) (*AddShopOutput, error) {
	client := pb.NewServiceClient(m.cli.Conn())
	return client.AddShopConfirm(ctx, in, opts...)
}

// AddShopCancel 创建店铺回滚
func (m *defaultService) AddShopCancel(ctx context.Context, in *AddShopInput, opts ...grpc.CallOption) (*AddShopOutput, error) {
	client := pb.NewServiceClient(m.cli.Conn())
	return client.AddShopCancel(ctx, in, opts...)
}
