// Code generated by goctl. DO NOT EDIT.
// Source: main.proto

package server

import (
	"context"

	"unit/shop/rpc/internal/logic"
	"unit/shop/rpc/internal/svc"
	"unit/shop/rpc/pb"
)

type ServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedServiceServer
}

func NewServiceServer(svcCtx *svc.ServiceContext) *ServiceServer {
	return &ServiceServer{
		svcCtx: svcCtx,
	}
}

// AddShop 创建店铺
func (s *ServiceServer) AddShop(ctx context.Context, in *pb.AddShopInput) (*pb.AddShopOutput, error) {
	l := logic.NewAddShopLogic(ctx, s.svcCtx)
	return l.AddShop(in)
}

// AddShopConfirm 创建店铺确认
func (s *ServiceServer) AddShopConfirm(ctx context.Context, in *pb.AddShopInput) (*pb.AddShopOutput, error) {
	l := logic.NewAddShopConfirmLogic(ctx, s.svcCtx)
	return l.AddShopConfirm(in)
}

// AddShopCancel 创建店铺回滚
func (s *ServiceServer) AddShopCancel(ctx context.Context, in *pb.AddShopInput) (*pb.AddShopOutput, error) {
	l := logic.NewAddShopCancelLogic(ctx, s.svcCtx)
	return l.AddShopCancel(in)
}
